services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypersonalpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./code:/code
    working_dir: /app